updated PR template
intelowlproject/IntelOwl pull request #1120
Opened 2022-07-22 16:11 UTC by mlodic

2022-07-22 16:14 UTC, devmrfitz commented
@mlodic For this to work, we necessarily need to PR to have more than 1 commit. Whereas our PR template actually recommends the user to have only 1 commit

2022-07-22 16:21 UTC, mlodic commented
you are right, thanks for pointing this out. I cry, I would like to automate all of this.

2022-07-22 16:24 UTC, mlodic commented
I removed the squash things because the maintainers would do that anyway so there is no need.

Plus, I added also a description about the case of the single commit.

2022-07-26 05:35 UTC, devmrfitz requested changes

2022-07-26 05:35 UTC, devmrfitz commented on .github/pull_request_template.md
> +(Please add to the PR name the issue/s that this PR would close if merged by using a [Github](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) keyw
We could just say "write `closes #123` in your first commit's message". That handles all cases

2022-08-16 15:48 UTC, merged