closes #959
intelowlproject/IntelOwl pull request #1134
Opened 2022-08-08 10:11 UTC by devmrfitz

# Description

Added expand/collapse button in Job result JSON viewer

## Related issues
#959 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

# Checklist

- [ ] I have read and understood the rules about [how to Contribute](https://intelowl.readthedocs.io/en/latest/Contribute.html) to this project
- [ ] The pull request is for the branch `develop`
- [ ] A new analyzer or connector was added, in which case:
    - [ ] [Usage](https://github.com/intelowlproject/IntelOwl/blob/master/docs/source/Usage.md) file was updated.
    - [ ] [Advanced-Usage](./Advanced-Usage.md) was updated (in case the analyzer/connector provides additional optional configuration).
    - [ ] Secrets were added in [env_file_app_template](https://github.com/intelowlproject/IntelOwl/blob/master/docker/env_file_app_template), [env_file_app_ci](https://github.com/certego/IntelOwl/blob/master/docker/env_file_app_ci) and in the [Installation](./Installation.md) docs, if necessary.
    - [ ] If the analyzer/connector requires mocked testing, `_monkeypatch()` was used in its class to apply the necessary decorators.
    - [ ] If a File analyzer was added, its name was explicitly defined in [test_file_scripts.py](https://github.com/intelowlproject/IntelOwl/blob/master/tests/analyzers_manager/test_file_scripts.py) (not required for Observable Analyzers).
- [ ] If external libraries/packages with restrictive licenses were used, they were added in the [Legal Notice](https://github.com/certego/IntelOwl/blob/master/.github/legal_notice.md) section.
- [ ] The tests gave 0 errors.
- [ ] Linters (`Black`, `Flake`, `Isort`) gave 0 errors. If you have correctly installed [pre-commit](https://intelowl.readthedocs.io/en/latest/Contribute.html#how-to-start-setup-project-and-development-instance), it does these checks and adjustments on your behalf.
- [ ] The commits were squashed into a single one (optional, they will be squashed anyway by the maintainer)
- [ ] If changes were made to an existing model/serializer/view, the docs were updated and regenerated (check `CONTRIBUTE.md`).
  
### Important Rules
- If your changes decrease the overall tests coverage (you will know after the Codecov CI job is done), you should add the required tests to fix the problem
- Everytime you make changes to the PR and you think the work is done, you should explicitly ask for a review

# Real World Example

Please delete if the PR is for bug fixing.
Otherwise, please provide the resulting raw JSON of a finished analysis (and, if you like, a screenshot of the results). This is to allow the maintainers to understand how the analyzer works.

2022-08-08 10:15 UTC, devmrfitz commented
![image](https://user-images.githubusercontent.com/58381523/183395697-73d789d2-a513-44e2-aea6-7413ffff48a0.png)

2022-08-08 11:04 UTC, drosetti requested changes
Good, but there are two bugs:
* If you open and then close the "report" key the toggle button stops working
* If you open "report" key and then "resolutions" key the toggle button stops working

2022-08-08 11:04 UTC, drosetti commented on frontend/src/components/jobs/result/utils/tables.jsx
> +            setCollapsed(collapsed ? false : 1);
I think this condition does not manage all the cases

2022-08-08 11:37 UTC, devmrfitz commented
>     * If you open and then close the "report" key the toggle button stops working
> 
>     * If you open "report" key and then "resolutions" key the toggle button stops working

This is the intended behaviour of `react-json-view`. When we click on "report", we set an individual collapse depth for it, hence, it does not respect the overall depth. The depth is still respected by other keys, for instance, Runtime Configuration, as seen below

![image](https://user-images.githubusercontent.com/58381523/183409552-b2554c01-f549-44d6-b038-f80a73d1168d.png)
![image](https://user-images.githubusercontent.com/58381523/183409577-08421a3a-07a6-4dad-9ab1-6f729adbe418.png)

2022-08-08 11:38 UTC, devmrfitz commented
> > ```
> > * If you open and then close the "report" key the toggle button stops working
> > 
> > * If you open "report" key and then "resolutions" key the toggle button stops working
> > ```
> 
> This is the intended behaviour of `react-json-view`. When we click on "report", we set an individual collapse depth for it, hence, it does not respect the overall depth. The depth is still respected by other keys, for instance, Runtime Configuration, as seen below
> 
> ![image](https://user-images.githubusercontent.com/58381523/183409552-b2554c01-f549-44d6-b038-f80a73d1168d.png) ![image](https://user-images.githubusercontent.com/58381523/183409577-08421a3a-07a6-4dad-9ab1-6f729adbe418.png)

@drosetti

2022-08-08 14:34 UTC, drosetti commented
Ok, but this makes the button not working, and it feels like a bug or an unexpected behaviour from an user perspective. I think the buttons always as to hide/show all the elements, but the arrow buttons have to show/hide the single value of the dict.

2022-08-08 18:48 UTC, devmrfitz commented
> Ok, but this makes the button not working, and it feels like a bug or an unexpected behaviour from an user perspective. I think the buttons always as to hide/show all the elements, but the arrow buttons have to show/hide the single value of the dict.

I tried all combinations at the [demo site](https://mac-s-g.github.io/react-json-view/demo/dist/), but this behaviour does not seem to be controllable in any manner

2022-08-09 07:47 UTC, drosetti commented
> > Ok, but this makes the button not working, and it feels like a bug or an unexpected behaviour from an user perspective. I think the buttons always as to hide/show all the elements, but the arrow buttons have to show/hide the single value of the dict.
> 
> I tried all combinations at the [demo site](https://mac-s-g.github.io/react-json-view/demo/dist/), but this behaviour does not seem to be controllable in any manner

Damn, you're right.
I think  the library behaviour is non-intuitive. I close this PR and write a comment about `collapsed` in the issue. Thanks for you tests!

2022-08-09 07:47 UTC, closed without merging