Disabled Playbooks are no Longer Visible in the UI
intelowlproject/IntelOwl pull request #1453
Opened 2023-01-26 21:32 UTC by AshirRashid

# Description

Disabled Playbooks are no Longer Visible in the UI (#1304)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue).

# Checklist

- [x] I have read and understood the rules about [how to Contribute](https://intelowl.readthedocs.io/en/latest/Contribute.html) to this project
- [x] The pull request is for the branch `develop`
- [ ] The tests gave 0 errors.
- [x] Linters (`Black`, `Flake`, `Isort`) gave 0 errors. If you have correctly installed [pre-commit](https://intelowl.readthedocs.io/en/latest/Contribute.html#how-to-start-setup-project-and-development-instance), it does these checks and adjustments on your behalf.
- [x] If the GUI has been modified, I have a provided a screenshot of the result in the PR.
The Disabled Playbook is no longer selectable in the scan form:
<img width="821" alt="CleanShot 2023-01-27 at 01 31 09@2x" src="https://user-images.githubusercontent.com/64663586/214955209-b5e6ddb5-3876-4c91-aa85-9c182b5c4523.png">

### Important Rules
- If you miss to compile the Checklist properly, your PR won't be reviewed by the maintainers.
- If your changes decrease the overall tests coverage (you will know after the Codecov CI job is done), you should add the required tests to fix the problem
- Everytime you make changes to the PR and you think the work is done, you should explicitly ask for a review. After being reviewed and received a "change request", you should explicitly ask for a review again once you have made the requested changes.

2023-01-26 21:45 UTC, AshirRashid commented
Running the command `black . --check --diff --exclude "migrations|venv"` leaves all files unchanged, but it returns an error int he test. The error is in a file that I haven't edited.

2023-01-27 08:31 UTC, 0ssigeno commented
The black error was my fault, you should be able to rebase `develop` and have the error fixed!

2023-01-27 08:31 UTC, mlodic requested changes

2023-01-27 08:31 UTC, mlodic commented on frontend/src/components/scan/ScanForm.jsx
> +          isDisabled: !v.verification.configured || v.disabled,
this is copy/pasted from analyzers/connectors. Playbooks do not have `!v.verification.configured` value. It is enough to set the second clause

2023-01-30 10:30 UTC, mlodic commented
ty!

2023-01-30 10:30 UTC, merged