Use cases (new playbooks and visualizers)
intelowlproject/IntelOwl pull request #1700
Opened 2023-05-18 17:04 UTC by mlodic

2023-05-19 07:42 UTC, 0ssigeno requested changes
The only thing that i would change on the visualizers, is that have a private method for each analyzer checked. Other than that, just a small fix on the report retrieval

2023-05-19 07:42 UTC, 0ssigeno commented on api_app/visualizers_manager/visualizers/domain_reputation_services.py
> +        if analyzer_report:
This will crash if the report does not exist.
The `if` condition should be converted to a `try except AnalyzerConfig.DoesNotExists`

2023-05-19 07:42 UTC, 0ssigeno commented on api_app/visualizers_manager/visualizers/domain_reputation_services.py
> +        if analyzer_report:
Same

2023-05-19 07:42 UTC, 0ssigeno commented on api_app/visualizers_manager/visualizers/domain_reputation_services.py
> +        if analyzer_report:
Same

2023-05-19 07:42 UTC, 0ssigeno commented on api_app/visualizers_manager/visualizers/domain_reputation_services.py
> +        if analyzer_report:
Same

2023-05-19 07:42 UTC, 0ssigeno commented on api_app/visualizers_manager/visualizers/domain_reputation_services.py
> +        if analyzer_report:
Same

2023-05-19 07:42 UTC, 0ssigeno commented on api_app/visualizers_manager/visualizers/domain_reputation_services.py
> +        if analyzer_report:
Same

2023-05-19 07:42 UTC, 0ssigeno commented on api_app/visualizers_manager/visualizers/domain_reputation_services.py
> +        if analyzer_report:
Same

2023-05-19 07:42 UTC, 0ssigeno commented on api_app/visualizers_manager/visualizers/ip_reputation_services.py
> +            hits = (
Same

2023-05-19 07:42 UTC, 0ssigeno commented on api_app/visualizers_manager/visualizers/ip_reputation_services.py
> +        if analyzer_report:
Same

2023-05-19 07:42 UTC, 0ssigeno commented on api_app/visualizers_manager/visualizers/ip_reputation_services.py
> +        if analyzer_report:
Same

2023-05-19 07:42 UTC, 0ssigeno commented on api_app/visualizers_manager/visualizers/ip_reputation_services.py
> +        if analyzer_report:
Same

2023-05-19 07:42 UTC, 0ssigeno commented on api_app/visualizers_manager/visualizers/ip_reputation_services.py
> +        if analyzer_report:
Same

2023-05-19 14:33 UTC, mlodic commented
complex method :P I do a refactor

2023-05-22 08:14 UTC, merged

2023-05-22 08:17 UTC, drosetti commented on api_app/visualizers_manager/classes.py
> +                )
Nevermind, i'll change this in the next pr with the fixes