added checkdmarc analyzer
intelowlproject/IntelOwl pull request #187
Opened 2020-09-09 20:27 UTC by goodlandsecurity

#145

2020-09-09 20:51 UTC, goodlandsecurity commented
i think i need some help with why the checks are failing as they don't appear to be from the files I added/edited. 

i made sure to follow the guide here: https://intelowl.readthedocs.io/en/latest/Contribute.html#create-a-pull-request

2020-09-10 18:25 UTC, Eshaan7 commented
@goodlandsecurity Thank you for your contribution. It's only a linter check that's failing. Please fix the merge conflicts and then run this `black . --exclude "migrations|venv"` command.

2020-09-11 11:10 UTC, Eshaan7 requested changes
Really glad you followed all steps as given in the docs. Just a few things I'd like to change..

2020-09-11 11:10 UTC, Eshaan7 commented on api_app/script_analyzers/observable_analyzers/checkdmarc.py
> +        except OSError as e:
The try-catch block here is redundant. The `run` function is itself wrapped into a try-catch block inside the `ObservableAnalyzer` class.

2020-09-11 11:10 UTC, Eshaan7 commented on api_app/script_analyzers/observable_analyzers/checkdmarc.py
> +            dmarc_info = stdout.decode("utf-8"), stderr
A better way would be,
```
if stderr:
  raise Exception(stderr.decode("utf-8"))
dmarc_str = stdout.decode("utf-8")
```

2020-09-11 15:33 UTC, goodlandsecurity commented
Of course! This is only the second project I've gotten to contribute to, but I am hopeful to add a few more analyzers though! I removed the try-catch block and used shutil to check if the required binary exists before running the analyzer

2020-09-14 14:16 UTC, Eshaan7 approved these changes

2020-09-14 14:17 UTC, merged

2020-09-14 16:10 UTC, Eshaan7 commented
Thank you for your contribution! The checkdmarc analyzer will be available with the next release which we will drop soon.