Added Urlscan
intelowlproject/IntelOwl pull request #199
Opened 2020-09-30 10:04 UTC by RamnathKumar181

The API allows 2 different functionalities:

- Submit_result: Takes URL as a parameter.
- Search: Takes IP, URL, Hash, or Domain as a parameter.

2020-09-30 10:23 UTC, RamnathKumar181 commented
The Travis build fails, but not on Urlscan. I have not made any changes to any of those files. How can I fix this?
The codefactor error could be fixed with a small change:
```
if not self.__api_key:
   raise AnalyzerRunException("no api key retrieved")
self.headers = {
   "Content-Type": "application/json",
   API-Key": self.__api_key,
}
```
I Hope, this is fine. :)

2020-09-30 12:23 UTC, Eshaan7 commented
> The codefactor error could be fixed with a small change

Can you make this change and commit/push again ?

2020-09-30 12:32 UTC, Eshaan7 commented on api_app/script_analyzers/observable_analyzers/urlscan.py
> +            session = requests.Session()
don't create a session here. Infact, create one in `run` function with the required `headers` and access it everywhere

2020-09-30 12:32 UTC, Eshaan7 commented on api_app/script_analyzers/observable_analyzers/urlscan.py
> +            time.sleep(10)
unnecessary line. `time.sleep` is already there inside the poll function

2020-09-30 12:32 UTC, Eshaan7 commented on env_file_app_template
> +URLSCAN_KEY=1a891838-6834-498e-a7cb-729e920c4f9c
You should never push your personal API key!! 
Also, the variable name is wrong. It should be `URLSCAN_API_KEY` as declared by you in `urlscan.py` and `analyzer_config.json`

The line should just be: `URLSCAN_API_KEY=`

2020-09-30 12:32 UTC, Eshaan7 commented on env_file_app_travis
> +URLSCAN_API_KEY=1a891838-6834-498e-a7cb-729e920c4f9c
replace this with `test` as done for others

2020-09-30 13:51 UTC, RamnathKumar181 commented
Hey @Eshaan7, thank you very much for pointing out. I have changed the API keys back to test and have addressed other CodeFactor and LGTM issues. I understand why Urlscan tests are failing (haven't passed the API key), but some other tests also are.

2020-10-01 09:02 UTC, Eshaan7 requested changes

2020-10-01 09:02 UTC, Eshaan7 commented on configuration/analyzer_config.json
> +      "urlscan_analysis": "search",
since you declared 2 different configurations, one for submit and other for search, so there's no need for passing an additiional config parameter.

2020-10-01 09:02 UTC, Eshaan7 commented on tests/utils.py
> +            {"urlscan_analysis": "search"},
continuing my previous comment, this is not required then either

2020-10-01 09:02 UTC, Eshaan7 commented on tests/test_observables.py
> +            {"urlscan_analysis": "search"},
same as above.

2020-10-01 09:02 UTC, Eshaan7 commented on tests/test_observables.py
> +            {"urlscan_analysis": "submit_result"},
same as above.

2020-10-01 09:02 UTC, Eshaan7 commented on api_app/script_analyzers/observable_analyzers/urlscan.py
> +                resp_json = resp.json()
why not just make it `result = resp.json()`

2020-10-01 09:04 UTC, Eshaan7 commented
> I understand why Urlscan tests are failing (haven't passed the API key), but some other tests also are.
@Eshaan7

Thankyou for making the fixes. Looking into this!

2020-10-01 09:08 UTC, Eshaan7 requested changes

2020-10-01 09:08 UTC, Eshaan7 commented on configuration/analyzer_config.json
> +      "urlscan_analysis": "search",
remove this unnecessary comma

2020-10-01 10:51 UTC, RamnathKumar181 commented
@Eshaan7 , I have made the changes you requested. Everything seems fine, except that the API key is not being passed. Let me know if something else needs to be done.

2020-10-01 15:43 UTC, Eshaan7 commented on api_app/script_analyzers/observable_analyzers/urlscan.py
> +max_tries: int = 10
ah, I missed this before. Just a small change: please declare these 2 variables inside the  `__poll_for_result` function only.

2020-10-01 16:40 UTC, Eshaan7 approved these changes

2020-10-03 12:32 UTC, Eshaan7 commented
I just needed to make a few fixes, merging it now.

Thankyou for your contribution, @RamnathKumar181 !

2020-10-03 12:32 UTC, merged

2020-10-05 07:40 UTC, mlodic commented on env_file_app_travis
> +DISABLE_LOGGING_TEST=False
why did you change this?

2020-10-05 07:52 UTC, mlodic commented on env_file_app_travis
> +URLSCAN_API_KEY=
why did you change this?