Added table cell component fixed text-wrapping issue.
intelowlproject/IntelOwl pull request #2166
Opened 2024-02-26 18:46 UTC by aryan-bhokare

closes #2051

# Description

Please include a summary of the change and link to the related issue.
Added a property to wrap the text in the cell so that is does not go out of bound.
Made a component for a `TableCell` component to improvise reusability.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

# Checklist

- [x] I have read and understood the rules about [how to Contribute](https://intelowl.readthedocs.io/en/latest/Contribute.html) to this project
- [x] The pull request is for the branch `develop`
- [ ] A new plugin (analyzer, connector, visualizer, playbook, pivot or ingestor) was added or changed, in which case:
    - [ ] I strictly followed the documentation ["How to create a Plugin"](https://intelowl.readthedocs.io/en/latest/Contribute.html#how-to-add-a-new-plugin)
    - [ ] [Usage](https://github.com/intelowlproject/IntelOwl/blob/master/docs/source/Usage.md) file was updated.
    - [ ] [Advanced-Usage](https://github.com/intelowlproject/IntelOwl/blob/master/docs/source/Advanced-Usage.md) was updated (in case the plugin provides additional optional configuration).
    - [ ] If the plugin requires mocked testing, `_monkeypatch()` was used in its class to apply the necessary decorators.
    - [ ] I have dumped the configuration from Django Admin using the `dumpplugin` command and added it in the project as a data migration. (["How to share a plugin with the community"](https://intelowl.readthedocs.io/en/latest/Contribute.html#how-to-share-your-plugin-with-the-community))
    - [ ] If a File analyzer was added and it supports a mimetype which is not already supported, you added a sample of that type inside the archive `test_files.zip` and you added the default tests for that mimetype in [test_classes.py](https://github.com/intelowlproject/IntelOwl/blob/master/tests/analyzers_manager/test_classes.py).
    - [ ] If you created a new analyzer and it is free (does not require API keys), please add it in the `FREE_TO_USE_ANALYZERS` playbook by following [this guide](https://intelowl.readthedocs.io/en/latest/Contribute.html#how-to-modify-a-plugin).
    - [ ] Check if it could make sense to add that analyzer/connector to other [freely available playbooks](https://intelowl.readthedocs.io/en/develop/Usage.html#list-of-pre-built-playbooks).
    - [ ] I have provided the resulting raw JSON of a finished analysis and a screenshot of the results.
- [ ] If external libraries/packages with restrictive licenses were used, they were added in the [Legal Notice](https://github.com/certego/IntelOwl/blob/master/.github/legal_notice.md) section.
- [x] Linters (`Black`, `Flake`, `Isort`) gave 0 errors. If you have correctly installed [pre-commit](https://intelowl.readthedocs.io/en/latest/Contribute.html#how-to-start-setup-project-and-development-instance), it does these checks and adjustments on your behalf.
- [ ] I have added tests for the feature/bug I solved (see `tests` folder). All the tests (new and old ones) gave 0 errors.
- [ ] If changes were made to an existing model/serializer/view, the docs were updated and regenerated (check [CONTRIBUTE.md](https://github.com/intelowlproject/IntelOwl/blob/master/docs/source/Contribute.md)).
- [x] If the GUI has been modified:
    - [x] I have a provided a screenshot of the result in the PR.
    - [ ] I have created new frontend tests for the new component or updated existing ones.

Screenshots:

![Screenshot from 2024-02-27 00-06-09](https://github.com/intelowlproject/IntelOwl/assets/92683836/e130ef3c-0814-4a1c-8ecf-f7c97b022c5f)

![Screenshot from 2024-02-27 00-05-42](https://github.com/intelowlproject/IntelOwl/assets/92683836/98e9a8ec-c0f7-4769-9bd4-4e79a36f83ef)

![Screenshot from 2024-02-27 00-05-08](https://github.com/intelowlproject/IntelOwl/assets/92683836/f1fa9711-f3ce-405d-aab9-a8793cf92653)

2024-02-26 18:47 UTC, aryan-bhokare commented
@drosetti PTAL .

Also I would like to component this 

```
      <ul className="d-flex flex-column align-items-start text-left text-break">
        {value?.sort().map((val) => (
          <li className="mb-2 pb-2" key={val}>
            {val}
          </li>
        ))}
      </ul>
```

As it's being reused a lot.

2024-02-27 09:41 UTC, drosetti commented
* There is a bug in the visualizer section (attached file)
![Screenshot from 2024-02-27 10-32-26](https://github.com/intelowlproject/IntelOwl/assets/55402684/33cd34af-56c3-4526-a0d5-0f66ef978a54)

* I also noticed a bug in the ingestor - playbook_to_execute: in case of long text it neither truncate nor break the playbook name.
 * Talking about your first screenshot: Do you think is possibile to have the 3 dots and the copyToClipboard in the elements instead of break the text ?
* In order to answer to your question: yes, a component for the list it would be great!

2024-02-27 19:12 UTC, aryan-bhokare commented
![Screenshot from 2024-02-28 00-38-59](https://github.com/intelowlproject/IntelOwl/assets/92683836/fc5f0d0e-e94a-4adf-823c-f20f861c3665)

![Screenshot from 2024-02-28 00-37-40](https://github.com/intelowlproject/IntelOwl/assets/92683836/114ba398-7100-4cf1-9319-33b020cc2e69)

![Screenshot from 2024-02-27 23-56-12](https://github.com/intelowlproject/IntelOwl/assets/92683836/3b81c8be-82e5-45f4-8932-29643573a295)

2024-02-28 09:50 UTC, drosetti commented
Thanks for the changes and the work you done! I'd like to talk with @mlodic about the UX. I know you did the changes I requested, but i'd like to have his opinion about it

2024-02-28 10:14 UTC, aryan-bhokare commented
> Thanks for the changes and the work you done! I'd like to talk with @mlodic about the UX. I know you did the changes I requested, but i'd like to have his opinion about it

Sure, Thanks!

2024-03-04 16:34 UTC, drosetti commented
@aryan-bhokare I talked with Matteo and we would like these changes:

* plugins -> analyzer -> supported types: ok the truncate, but it's too early, there is lots of free space available (see screenshot)
![Screenshot from 2024-03-04 17-30-40](https://github.com/intelowlproject/IntelOwl/assets/55402684/01a87c73-4eb3-470b-836e-5e6aaaf81182)
* plugins -> visualizer -> playbook connected to: truncate too early
* plugins -> ingestor -> playbook_to_execute: truncate with the `...`
* plugins -> playbooks -> analyzer/connector/...: truncate too early
* jobs -> playbook executued: add truncate and copy feature

Thanks!

2024-03-06 08:09 UTC, aryan-bhokare commented
> @aryan-bhokare I talked with Matteo and we would like these changes:
> 
> * plugins -> analyzer -> supported types: ok the truncate, but it's too early, there is lots of free space available (see screenshot)
>   ![Screenshot from 2024-03-04 17-30-40](https://private-user-images.githubusercontent.com/55402684/309828588-01a87c73-4eb3-470b-836e-5e6aaaf81182.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MTI3MzYsIm5iZiI6MTcwOTcxMjQzNiwicGF0aCI6Ii81NTQwMjY4NC8zMDk4Mjg1ODgtMDFhODdjNzMtNGViMy00NzBiLTgzNmUtNWU2YWFhZjgxMTgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDA4MDcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllNTg5M2MyNTliODk4MGE3ZDQxODg3MGYzYWFlZWFjNTQ0MjVlYjFkOTVlMGNmYTA5ZTJhMGYxNzE0OTcyMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9UKb-eatG2-KOjLTCqTP5mF8_4lESiqxgbjW0kPi5-w)
> * plugins -> visualizer -> playbook connected to: truncate too early
> * plugins -> ingestor -> playbook_to_execute: truncate with the `...`
> * plugins -> playbooks -> analyzer/connector/...: truncate too early
> * jobs -> playbook executued: add truncate and copy feature
> 
> Thanks!

I'll have to truncate dynammically then.
let me check if we have something

2024-03-06 14:17 UTC, drosetti commented
I think the best way to truncate text is to create the div of the correct dimension for the ul elements and then use the truncate from bootstrap. Idk if this can help you, if you have some doubt let me know :)

2024-03-08 05:53 UTC, aryan-bhokare commented
@drosetti I have made all the requested changes.

2024-03-11 10:01 UTC, drosetti requested changes
My apologizes to request you to "revert" something about the UX, but can you restore the supported_types in plugin -> analyzers and the elements in the columns of playbooks -> analyzers/connectors/... to break the text instead of truncate ? Even if I think it's more beautiful the truncate version, the text break show all the type or plugin name and it could be more useful.

Thanks for your work!

Edit: I think it should be quite easy, you structured well the components so it should be just a flag.

2024-03-11 16:07 UTC, aryan-bhokare commented on frontend/src/components/common/TableCell.jsx
> +    </div>
ohh yes... didn't think of it thanks!

2024-03-14 04:14 UTC, aryan-bhokare commented on frontend/src/components/jobs/table/jobTableColumns.jsx
> +            </CopyToClipboardButton>
I don't see this being used multiple times it's only specific to playbook to execute.

2024-03-14 04:23 UTC, aryan-bhokare commented on frontend/src/components/common/TableCell.jsx
> +    </div>
done

2024-03-14 04:23 UTC, aryan-bhokare commented on frontend/src/components/jobs/table/jobTableColumns.jsx
> +      <TableCell job={job} isCopyToClipboard value={value} />
done

2024-03-14 04:23 UTC, aryan-bhokare commented on frontend/src/components/plugins/types/utils.jsx
> +            </li>
done

2024-03-14 04:24 UTC, aryan-bhokare commented on frontend/src/components/plugins/types/pluginTableColumns.jsx
> +    Cell: ({ value }) => <TableCellList value={value} size={25} />,
done

2024-03-14 04:24 UTC, aryan-bhokare commented on frontend/src/components/jobs/table/jobTableColumns.jsx
> +            </CopyToClipboardButton>
I don't this this login being repeated. It's specific to playbook to execute only

2024-03-14 08:36 UTC, drosetti commented on frontend/src/components/jobs/table/jobTableColumns.jsx
> +            </CopyToClipboardButton>
I'm talking about:
```
playbooks?.find(
  (playbook) => playbook.id === job.playbook_to_execute,
)?.name || "Custom Analysis"
```
It's not used in other files, but in this one is used twice

2024-03-17 03:47 UTC, aryan-bhokare commented on frontend/src/components/jobs/table/jobTableColumns.jsx
> +            </CopyToClipboardButton>
done

2024-03-19 08:48 UTC, drosetti commented
@aryan-bhokare please when you think the code is ready request me the re-review. In this way I'll know if I have to look at the code or I'll think you are still working

2024-03-19 08:51 UTC, aryan-bhokare commented
> @aryan-bhokare please when you think the code is ready request me the re-review. In this way I'll know if I have to look at the code or I'll think you are still working

ohh sorry can you review it @drosetti ?

2024-03-19 10:03 UTC, drosetti requested changes
Just last request, can you change different keys ? I noticed some errors in the console:
![Screenshot from 2024-03-19 11-03-21](https://github.com/intelowlproject/IntelOwl/assets/55402684/13636ea7-c22f-4ffa-ab11-383653fc625f)

2024-03-20 09:08 UTC, drosetti approved these changes

2024-03-20 09:08 UTC, merged

2024-03-20 09:08 UTC, drosetti commented
Top! Thanks for your contribution :)

2024-03-20 11:24 UTC, aryan-bhokare commented
> Top! Thanks for your contribution :)

Happy to contribute 😁.