fixes #1698 - hfinger analyzer
intelowlproject/IntelOwl pull request #2241
Opened 2024-04-03 18:03 UTC by moonpatel

Closes #1698 

# Description
Hfinger analyzer for fingerprinting HTTP requests

## Type of change
New analyzer

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

# Checklist

- [x] I have read and understood the rules about [how to Contribute](https://intelowl.readthedocs.io/en/latest/Contribute.html) to this project
- [x] The pull request is for the branch `develop`
- [x] A new plugin (analyzer, connector, visualizer, playbook, pivot or ingestor) was added or changed, in which case:
    - [x] I strictly followed the documentation ["How to create a Plugin"](https://intelowl.readthedocs.io/en/latest/Contribute.html#how-to-add-a-new-plugin)
    - [ ] [Usage](https://github.com/intelowlproject/IntelOwl/blob/master/docs/source/Usage.md) file was updated.
    - [ ] [Advanced-Usage](https://github.com/intelowlproject/IntelOwl/blob/master/docs/source/Advanced-Usage.md) was updated (in case the plugin provides additional optional configuration).
    - [x] If the plugin requires mocked testing, `_monkeypatch()` was used in its class to apply the necessary decorators.
    - [x] I have dumped the configuration from Django Admin using the `dumpplugin` command and added it in the project as a data migration. (["How to share a plugin with the community"](https://intelowl.readthedocs.io/en/latest/Contribute.html#how-to-share-your-plugin-with-the-community))
    - [ ] If a File analyzer was added and it supports a mimetype which is not already supported, you added a sample of that type inside the archive `test_files.zip` and you added the default tests for that mimetype in [test_classes.py](https://github.com/intelowlproject/IntelOwl/blob/master/tests/analyzers_manager/test_classes.py).
    - [x] If you created a new analyzer and it is free (does not require API keys), please add it in the `FREE_TO_USE_ANALYZERS` playbook by following [this guide](https://intelowl.readthedocs.io/en/latest/Contribute.html#how-to-modify-a-plugin).
    - [ ] Check if it could make sense to add that analyzer/connector to other [freely available playbooks](https://intelowl.readthedocs.io/en/develop/Usage.html#list-of-pre-built-playbooks).
    - [x] I have provided the resulting raw JSON of a finished analysis and a screenshot of the results. 
    - [x] I have added that raw JSON sample to the `MockUpResponse` of the `_monkeypatch()` method. This serves us to provide a valid sample for testing.
- [ ] If external libraries/packages with restrictive licenses were used, they were added in the [Legal Notice](https://github.com/certego/IntelOwl/blob/master/.github/legal_notice.md) section.
- [x] Linters (`Black`, `Flake`, `Isort`) gave 0 errors. If you have correctly installed [pre-commit](https://intelowl.readthedocs.io/en/latest/Contribute.html#how-to-start-setup-project-and-development-instance), it does these checks and adjustments on your behalf.
- [ ] I have added tests for the feature/bug I solved (see `tests` folder). All the tests (new and old ones) gave 0 errors.
- [ ] If changes were made to an existing model/serializer/view, the docs were updated and regenerated (check [CONTRIBUTE.md](https://github.com/intelowlproject/IntelOwl/blob/master/docs/source/Contribute.md)).
- [ ] If the GUI has been modified:
    - [ ] I have a provided a screenshot of the result in the PR.
    - [ ] I have created new frontend tests for the new component or updated existing ones.
- [ ] After you had submitted the PR, if `DeepSource`, `Django Doctors` or other third-party linters have triggered any alerts during the CI checks, I have solved those alerts.

### Important Rules
- If you miss to compile the Checklist properly, your PR won't be reviewed by the maintainers.
- Everytime you make changes to the PR and you think the work is done, you should explicitly ask for a review. After being reviewed and received a "change request", you should explicitly ask for a review again once you have made the requested changes.

2024-04-03 20:42 UTC, moonpatel commented
Raw json:
```
[
  {
    "epoch_time": "1388111476.787707000",
    "ip_src": "192.168.1.138",
    "ip_dst": "173.194.115.80",
    "port_src": "49209",
    "port_dst": "80",
    "fingerprint": "2.4|1|0.5||2.4|1.2|GE|1|ac,ac-la,us-ag,ac-en,ho,co|ac:te-ht,ap-xh+xm,as-as/ac-la:75ef792f/us-ag:ca0c4d71/ac-en:gz,de/co:Ke-Al|||"
  },
  {
    "epoch_time": "1388111477.142485000",
    "ip_src": "192.168.1.138",
    "ip_dst": "66.225.230.141",
    "port_src": "49220",
    "port_dst": "80",
    "fingerprint": "1.5|3|1.0|html|||GE|1|ac,re,ac-la,us-ag,ac-en,ho,co|ac:te-ht,ap-xh+xm,as-as/ac-la:75ef792f/us-ag:ca0c4d71/ac-en:gz,de/co:Ke-Al|||"
  },
  {
    "epoch_time": "1388111477.382351000",
    "ip_src": "192.168.1.138",
    "ip_dst": "93.170.131.2",
    "port_src": "49219",
    "port_dst": "80",
    "fingerprint": "0.8|1|0.7|php|||GE|1|ac,re,ac-la,us-ag,ac-en,co,ho|ac:te-ht,ap-xh+xm,as-as/ac-la:75ef792f/us-ag:ca0c4d71/ac-en:gz,de/co:Ke-Al|||"
  },
  {
    "epoch_time": "1388111478.122647000",
    "ip_src": "192.168.1.138",
    "ip_dst": "194.116.187.24",
    "port_src": "49223",
    "port_dst": "80",
    "fingerprint": "1.5|3|1.0|php|||GE|1|ac,re,ac-la,us-ag,ac-en,co,ho|ac:te-ht,ap-xh+xm,as-as/ac-la:75ef792f/us-ag:ca0c4d71/ac-en:gz,de/co:Ke-Al|||"
  },
  {
    "epoch_time": "1388111478.791157000",
    "ip_src": "192.168.1.138",
    "ip_dst": "74.220.203.53",
    "port_src": "49211",
    "port_dst": "80",
    "fingerprint": "1.3|3|0.8|php|||GE|1|ac,re,ac-la,us-ag,ac-en,co,ho|ac:te-ht,ap-xh+xm,as-as/ac-la:75ef792f/us-ag:ca0c4d71/ac-en:gz,de/co:Ke-Al|||"
  },
  {
    "epoch_time": "1388111478.928841000",
    "ip_src": "192.168.1.138",
    "ip_dst": "146.255.46.1",
    "port_src": "49218",
    "port_dst": "80",
    "fingerprint": "1.6|6|0.8|php|||GE|1|ac,re,ac-la,us-ag,ac-en,co,ho|ac:te-ht,ap-xh+xm,as-as/ac-la:75ef792f/us-ag:ca0c4d71/ac-en:gz,de/co:Ke-Al|||"
  },
  {
    "epoch_time": "1388111479.092094000",
    "ip_src": "192.168.1.138",
    "ip_dst": "93.95.103.12",
    "port_src": "49222",
    "port_dst": "80",
    "fingerprint": "1.6|3|0.9|php|1.0|0.7|GE|1|ac,re,ac-la,us-ag,ac-en,co,ho|ac:te-ht,ap-xh+xm,as-as/ac-la:75ef792f/us-ag:ca0c4d71/ac-en:gz,de/co:Ke-Al|||"
  },
  {
    "epoch_time": "1388111479.291795000",
    "ip_src": "192.168.1.138",
    "ip_dst": "188.116.34.246",
    "port_src": "49212",
    "port_dst": "80",
    "fingerprint": "2.0|1|0.0||2.0|1.5|GE|1|ac,re,ac-la,us-ag,ac-en,co,ho|ac:te-ht,ap-xh+xm,as-as/ac-la:75ef792f/us-ag:ca0c4d71/ac-en:gz,de/co:Ke-Al|||"
  },
  {
    "epoch_time": "1388111479.731096000",
    "ip_src": "192.168.1.138",
    "ip_dst": "188.116.34.246",
    "port_src": "49224",
    "port_dst": "80",
    "fingerprint": "2.9|1|0.7||2.9|2.9|GE|1|ac,re,ac-la,us-ag,ac-en,co,ho|ac:te-ht,ap-xh+xm,as-as/ac-la:75ef792f/us-ag:ca0c4d71/ac-en:gz,de/co:Ke-Al|||"
  },
  {
    "epoch_time": "1388111479.968603000",
    "ip_src": "192.168.1.138",
    "ip_dst": "188.116.34.246",
    "port_src": "49224",
    "port_dst": "80",
    "fingerprint": "1.0|1|1.0|js|||GE|1|ac,re,ac-la,us-ag,ac-en,ho,co|ac:9272bf4b/ac-la:75ef792f/us-ag:ca0c4d71/ac-en:gz,de/co:Ke-Al|||"
  },
  {
    "epoch_time": "1388111481.169949000",
    "ip_src": "192.168.1.138",
    "ip_dst": "188.116.34.246",
    "port_src": "49224",
    "port_dst": "80",
    "fingerprint": "0.8|1|0.8|html|||GE|1|ac,re,ac-la,us-ag,ac-en,ho,co|ac:te-ht,ap-xh+xm,as-as/ac-la:75ef792f/us-ag:ca0c4d71/ac-en:gz,de/co:Ke-Al|||"
  },
  {
    "epoch_time": "1388111481.400438000",
    "ip_src": "192.168.1.138",
    "ip_dst": "188.116.34.246",
    "port_src": "49224",
    "port_dst": "80",
    "fingerprint": "1.1|1|1.1|html|||GE|1|ac,re,ac-la,us-ag,ac-en,ho,co|ac:te-ht,ap-xh+xm,as-as/ac-la:75ef792f/us-ag:ca0c4d71/ac-en:gz,de/co:Ke-Al|||"
  },
  {
    "epoch_time": "1388111482.360591000",
    "ip_src": "192.168.1.138",
    "ip_dst": "206.190.56.190",
    "port_src": "49225",
    "port_dst": "80",
    "fingerprint": "1.5|5|0.7|jpg|||GE|1|ac,re,ac-la,us-ag,ac-en,ho,co|ac:bb12577a/ac-la:75ef792f/us-ag:ca0c4d71/ac-en:gz,de/co:Ke-Al|||"
  },
  {
    "epoch_time": "1388111486.392734000",
    "ip_src": "192.168.1.138",
    "ip_dst": "188.116.34.246",
    "port_src": "49224",
    "port_dst": "80",
    "fingerprint": "1.0|1|1.0|html|||GE|1|ac,re,ac-la,us-ag,ac-en,ho,co|ac:te-ht,ap-xh+xm,as-as/ac-la:75ef792f/us-ag:ca0c4d71/ac-en:gz,de/co:Ke-Al|||"
  },
  {
    "epoch_time": "1388111486.822345000",
    "ip_src": "192.168.1.138",
    "ip_dst": "188.116.34.246",
    "port_src": "49224",
    "port_dst": "80",
    "fingerprint": "1.1|1|1.0|ico|||GE|1|ac,ac-en,us-ag,ho,co|ac:as-as/ac-en:gz,de/us-ag:ca0c4d71/co:Ke-Al|||"
  },
  {
    "epoch_time": "1388111486.992352000",
    "ip_src": "192.168.1.138",
    "ip_dst": "188.116.34.246",
    "port_src": "49224",
    "port_dst": "80",
    "fingerprint": "1.3|3|0.7|jpg|||GE|1|ac,re,ac-la,us-ag,ac-en,ho,co|ac:bb12577a/ac-la:75ef792f/us-ag:ca0c4d71/ac-en:gz,de/co:Ke-Al|||"
  },
  {
    "epoch_time": "1388111486.999332000",
    "ip_src": "192.168.1.138",
    "ip_dst": "188.116.34.246",
    "port_src": "49227",
    "port_dst": "80",
    "fingerprint": "1.2|3|0.7|gif|||GE|1|ac,re,ac-la,us-ag,ac-en,ho,co|ac:bb12577a/ac-la:75ef792f/us-ag:ca0c4d71/ac-en:gz,de/co:Ke-Al|||"
  },
  {
    "epoch_time": "1388111487.012956000",
    "ip_src": "192.168.1.138",
    "ip_dst": "188.116.34.246",
    "port_src": "49228",
    "port_dst": "80",
    "fingerprint": "1.3|3|0.7|gif|||GE|1|ac,re,ac-la,us-ag,ac-en,ho,co|ac:bb12577a/ac-la:75ef792f/us-ag:ca0c4d71/ac-en:gz,de/co:Ke-Al|||"
  },
  {
    "epoch_time": "1388111487.020503000",
    "ip_src": "192.168.1.138",
    "ip_dst": "188.116.34.246",
    "port_src": "49229",
    "port_dst": "80",
    "fingerprint": "1.3|3|0.7|jpg|||GE|1|ac,re,ac-la,us-ag,ac-en,ho,co|ac:bb12577a/ac-la:75ef792f/us-ag:ca0c4d71/ac-en:gz,de/co:Ke-Al|||"
  },
  {
    "epoch_time": "1388111487.034579000",
    "ip_src": "192.168.1.138",
    "ip_dst": "188.116.34.246",
    "port_src": "49231",
    "port_dst": "80",
    "fingerprint": "1.3|3|0.7|jpg|||GE|1|ac,re,ac-la,us-ag,ac-en,ho,co|ac:bb12577a/ac-la:75ef792f/us-ag:ca0c4d71/ac-en:gz,de/co:Ke-Al|||"
  },
  {
    "epoch_time": "1388111487.042400000",
    "ip_src": "192.168.1.138",
    "ip_dst": "188.116.34.246",
    "port_src": "49230",
    "port_dst": "80",
    "fingerprint": "1.3|3|0.7|jpg|||GE|1|ac,re,ac-la,us-ag,ac-en,ho,co|ac:bb12577a/ac-la:75ef792f/us-ag:ca0c4d71/ac-en:gz,de/co:Ke-Al|||"
  },
  {
    "epoch_time": "1388111487.163120000",
    "ip_src": "192.168.1.138",
    "ip_dst": "188.116.34.246",
    "port_src": "49224",
    "port_dst": "80",
    "fingerprint": "1.3|3|0.7|jpg|||GE|1|ac,re,ac-la,us-ag,ac-en,ho,co|ac:bb12577a/ac-la:75ef792f/us-ag:ca0c4d71/ac-en:gz,de/co:Ke-Al|||"
  },
  {
    "epoch_time": "1388111487.170618000",
    "ip_src": "192.168.1.138",
    "ip_dst": "188.116.34.246",
    "port_src": "49227",
    "port_dst": "80",
    "fingerprint": "1.3|3|0.7|jpg|||GE|1|ac,re,ac-la,us-ag,ac-en,ho,co|ac:bb12577a/ac-la:75ef792f/us-ag:ca0c4d71/ac-en:gz,de/co:Ke-Al|||"
  },
  {
    "epoch_time": "1388111487.191402000",
    "ip_src": "192.168.1.138",
    "ip_dst": "188.116.34.246",
    "port_src": "49228",
    "port_dst": "80",
    "fingerprint": "1.2|3|0.6|jpg|||GE|1|ac,re,ac-la,us-ag,ac-en,ho,co|ac:bb12577a/ac-la:75ef792f/us-ag:ca0c4d71/ac-en:gz,de/co:Ke-Al|||"
  },
  {
    "epoch_time": "1388111487.197397000",
    "ip_src": "192.168.1.138",
    "ip_dst": "188.116.34.246",
    "port_src": "49229",
    "port_dst": "80",
    "fingerprint": "1.2|3|0.7|gif|||GE|1|ac,re,ac-la,us-ag,ac-en,ho,co|ac:bb12577a/ac-la:75ef792f/us-ag:ca0c4d71/ac-en:gz,de/co:Ke-Al|||"
  },
  {
    "epoch_time": "1388111487.212925000",
    "ip_src": "192.168.1.138",
    "ip_dst": "188.116.34.246",
    "port_src": "49231",
    "port_dst": "80",
    "fingerprint": "1.3|3|0.8|png|||GE|1|ac,re,ac-la,us-ag,ac-en,ho,co|ac:bb12577a/ac-la:75ef792f/us-ag:ca0c4d71/ac-en:gz,de/co:Ke-Al|||"
  },
  {
    "epoch_time": "1388111487.228890000",
    "ip_src": "192.168.1.138",
    "ip_ [...]

2024-04-04 08:46 UTC, 0ssigeno approved these changes
lgtm

2024-04-04 09:09 UTC, mlodic requested changes
great! just 2 little things

2024-04-04 09:09 UTC, mlodic commented on docker/Dockerfile
> +    vim libldap2-dev libfuzzy-dev net-tools python3-psycopg2 git apache2-utils tshark \
please comment that tshark is required for this analyzer otherwise we will forget it

2024-04-04 09:09 UTC, mlodic commented on api_app/analyzers_manager/migrations/0078_analyzer_config_hfinger.py
> +    "maximum_tlp": "AMBER",
RED cause this is an internal service

2024-04-04 10:47 UTC, 0ssigeno commented
Don't worry about the tests. I fucked up something in`develop`. Once @mlodic approves the PR is mergeable

2024-04-04 10:57 UTC, mlodic approved these changes

2024-04-13 20:01 UTC, moonpatel commented
Hey @mlodic can you merge this PR now?

2024-04-15 07:22 UTC, merged