Fixes Blint#2232
intelowlproject/IntelOwl pull request #2257
Opened 2024-04-09 20:26 UTC by g4ze

closes #2232
# Description

Please include a summary of the change and link to the related issue.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

# Checklist

- [ ] I have read and understood the rules about [how to Contribute](https://intelowl.readthedocs.io/en/latest/Contribute.html) to this project
- [ ] The pull request is for the branch `develop`
- [ ] A new plugin (analyzer, connector, visualizer, playbook, pivot or ingestor) was added or changed, in which case:
    - [ ] I strictly followed the documentation ["How to create a Plugin"](https://intelowl.readthedocs.io/en/latest/Contribute.html#how-to-add-a-new-plugin)
    - [ ] [Usage](https://github.com/intelowlproject/IntelOwl/blob/master/docs/source/Usage.md) file was updated.
    - [ ] [Advanced-Usage](https://github.com/intelowlproject/IntelOwl/blob/master/docs/source/Advanced-Usage.md) was updated (in case the plugin provides additional optional configuration).
    - [ ] If the plugin requires mocked testing, `_monkeypatch()` was used in its class to apply the necessary decorators.
    - [ ] I have dumped the configuration from Django Admin using the `dumpplugin` command and added it in the project as a data migration. (["How to share a plugin with the community"](https://intelowl.readthedocs.io/en/latest/Contribute.html#how-to-share-your-plugin-with-the-community))
    - [ ] If a File analyzer was added and it supports a mimetype which is not already supported, you added a sample of that type inside the archive `test_files.zip` and you added the default tests for that mimetype in [test_classes.py](https://github.com/intelowlproject/IntelOwl/blob/master/tests/analyzers_manager/test_classes.py).
    - [ ] If you created a new analyzer and it is free (does not require API keys), please add it in the `FREE_TO_USE_ANALYZERS` playbook by following [this guide](https://intelowl.readthedocs.io/en/latest/Contribute.html#how-to-modify-a-plugin).
    - [ ] Check if it could make sense to add that analyzer/connector to other [freely available playbooks](https://intelowl.readthedocs.io/en/develop/Usage.html#list-of-pre-built-playbooks).
    - [ ] I have provided the resulting raw JSON of a finished analysis and a screenshot of the results. 
    - [ ] I have added that raw JSON sample to the `MockUpResponse` of the `_monkeypatch()` method. This serves us to provide a valid sample for testing.
- [ ] If external libraries/packages with restrictive licenses were used, they were added in the [Legal Notice](https://github.com/certego/IntelOwl/blob/master/.github/legal_notice.md) section.
- [ ] Linters (`Black`, `Flake`, `Isort`) gave 0 errors. If you have correctly installed [pre-commit](https://intelowl.readthedocs.io/en/latest/Contribute.html#how-to-start-setup-project-and-development-instance), it does these checks and adjustments on your behalf.
- [ ] I have added tests for the feature/bug I solved (see `tests` folder). All the tests (new and old ones) gave 0 errors.
- [ ] If changes were made to an existing model/serializer/view, the docs were updated and regenerated (check [CONTRIBUTE.md](https://github.com/intelowlproject/IntelOwl/blob/master/docs/source/Contribute.md)).
- [ ] If the GUI has been modified:
    - [ ] I have a provided a screenshot of the result in the PR.
    - [ ] I have created new frontend tests for the new component or updated existing ones.
- [ ] After you had submitted the PR, if `DeepSource`, `Django Doctors` or other third-party linters have triggered any alerts during the CI checks, I have solved those alerts.

### Important Rules
- If you miss to compile the Checklist properly, your PR won't be reviewed by the maintainers.
- Everytime you make changes to the PR and you think the work is done, you should explicitly ask for a review. After being reviewed and received a "change request", you should explicitly ask for a review again once you have made the requested changes.

2024-04-09 20:29 UTC, g4ze commented
Hi there @mlodic !
Facing a permission error while trying to make directory here. This didnt heppen previously for making update databases of analyzers.
Could you please go through this?
![Screenshot_20240410_015845](https://github.com/intelowlproject/IntelOwl/assets/102874321/748f6b90-d6d4-47c4-a851-b542fdd5e3ed)

2024-04-10 07:42 UTC, mlodic commented
if you leverage a new folder for this analyzer like Yara did, you should follow the same pattern and create that directory in the dockerfile

2024-04-11 15:13 UTC, g4ze commented
tlp green?

2024-04-11 15:34 UTC, g4ze commented
![image](https://github.com/intelowlproject/IntelOwl/assets/102874321/3799c4a5-f72d-4d11-aafd-33be8e95ae4f)
For the ci check failing, it says that 2.1.1 isint available even tho it builds correctly on my local. Is there somehing I'm overlooking here :crying_cat_face:

2024-04-11 15:46 UTC, g4ze commented
@mlodic rest lgtm could you pls review?

2024-04-11 15:52 UTC, mlodic commented
strange error, I force the analysis again

2024-04-11 16:02 UTC, mlodic requested changes
please pretty format an example output otherwise I can't understand the possible results.

2024-04-11 16:02 UTC, mlodic commented on api_app/analyzers_manager/file_analyzers/blint_scan.py
> +        return response
you need to cleanup the file system otherwise you would keep useless data there until you break the app

2024-04-11 16:02 UTC, mlodic commented on api_app/analyzers_manager/file_analyzers/blint_scan.py
> +        logger.info(f"response: {response}")
this should be debug only

2024-04-11 16:02 UTC, mlodic commented on api_app/analyzers_manager/file_analyzers/blint_scan.py
> +        return response
we should always return a dict

2024-04-11 16:08 UTC, g4ze commented on api_app/playbooks_manager/migrations/0031_add_blint_to_free_analyzers.py
> +# This file is a part of IntelOwl https://github.com/intelowlproject/IntelOwl
sure! should I add Zippy as well?

2024-04-11 16:13 UTC, mlodic commented on api_app/playbooks_manager/migrations/0031_add_blint_to_free_analyzers.py
> +# This file is a part of IntelOwl https://github.com/intelowlproject/IntelOwl
no cause that's an particular use case

2024-04-11 18:14 UTC, g4ze commented on api_app/analyzers_manager/migrations/0078_analyzer_config_blint.py
> +        "application/x-binary",
Do you know of any place where i can download safe samples of such files? It's a bit hard to find such sample files.

2024-04-11 19:12 UTC, g4ze commented on api_app/analyzers_manager/migrations/0078_analyzer_config_blint.py
> +        "application/x-binary",
i particularly need `.aab` file.

2024-04-19 02:04 UTC, g4ze commented
@mlodic kindly review

2024-05-11 18:04 UTC, g4ze commented
hey @mlodic ! I see that you have have incorporated some more changes to the code. Is there anything left to be changed or worked upon here (for me)?

2024-05-13 08:17 UTC, merged