[Analyzer] UltraDNS #1783
intelowlproject/IntelOwl pull request #2620
Opened 2024-12-26 15:29 UTC by pranjalg1331

# Description

I have added two analyzers for UltraDNS ( ultradns resolver and ultradns malicious detector). I have added the migration files for both of the analysers and have also added the migration files to add them both to the free_to_use playbook.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

# Checklist

- [x ] I have read and understood the rules about [how to Contribute](https://intelowlproject.github.io/docs/IntelOwl/contribute/) to this project
- [ x] The pull request is for the branch `develop`
- [ x] A new plugin (analyzer, connector, visualizer, playbook, pivot or ingestor) was added or changed, in which case:
    - [x ] I strictly followed the documentation ["How to create a Plugin"](https://intelowlproject.github.io/docs/IntelOwl/contribute/#how-to-add-a-new-plugin)
    - [ ] [Usage](https://github.com/intelowlproject/docs/blob/main/docs/IntelOwl/usage.md) file was updated.
    - [ ] [Advanced-Usage](https://github.com/intelowlproject/docs/blob/main/docs/IntelOwl/advanced_usage.md) was updated (in case the plugin provides additional optional configuration).
    - [ x] I have dumped the configuration from Django Admin using the `dumpplugin` command and added it in the project as a data migration. (["How to share a plugin with the community"](https://intelowlproject.github.io/docs/IntelOwl/contribute/#how-to-share-your-plugin-with-the-community))
    - [ ] If a File analyzer was added and it supports a mimetype which is not already supported, you added a sample of that type inside the archive `test_files.zip` and you added the default tests for that mimetype in [test_classes.py](https://github.com/intelowlproject/IntelOwl/blob/master/tests/api_app/analyzers_manager/test_classes.py).
    - [ x] If you created a new analyzer and it is free (does not require any API key), please add it in the `FREE_TO_USE_ANALYZERS` playbook by following [this guide](https://intelowlproject.github.io/docs/IntelOwl/contribute/#how-to-modify-a-plugin).
    - [ ] Check if it could make sense to add that analyzer/connector to other [freely available playbooks](https://intelowlproject.github.io/docs/IntelOwl/usage/#list-of-pre-built-playbooks).
    - [ ] I have provided the resulting raw JSON of a finished analysis and a screenshot of the results.
    - [ ] If the plugin interacts with an external service, I have created an attribute called precisely `url` that contains this information. This is required for Health Checks. 
    - [ x] If the plugin requires mocked testing, `_monkeypatch()` was used in its class to apply the necessary decorators.
    - [ ] I have added that raw JSON sample to the `MockUpResponse` of the `_monkeypatch()` method. This serves us to provide a valid sample for testing.
- [ ] If external libraries/packages with restrictive licenses were used, they were added in the [Legal Notice](https://github.com/certego/IntelOwl/blob/master/.github/legal_notice.md) section.
- [ x] Linters (`Black`, `Flake`, `Isort`) gave 0 errors. If you have correctly installed [pre-commit](https://intelowlproject.github.io/docs/IntelOwl/contribute/#how-to-start-setup-project-and-development-instance), it does these checks and adjustments on your behalf.
- [ ] I have added tests for the feature/bug I solved (see `tests` folder). All the tests (new and old ones) gave 0 errors.
- [ ] If changes were made to an existing model/serializer/view, the docs were updated and regenerated (check [CONTRIBUTE.md](https://github.com/intelowlproject/IntelOwl/blob/master/docs/source/Contribute.md)).
- [ ] If the GUI has been modified:
    - [ ] I have a provided a screenshot of the result in the PR.
    - [ ] I have created new frontend tests for the new component or updated existing ones.
- [ ] After you had submitted the PR, if `DeepSource`, `Django Doctors` or other third-party linters have triggered any alerts during the CI checks, I have solved those alerts.

### Important Rules
- If you miss to compile the Checklist properly, your PR won't be reviewed by the maintainers.
- Everytime you make changes to the PR and you think the work is done, you should explicitly ask for a review. After being reviewed and received a "change request", you should explicitly ask for a review again once you have made the requested changes.

2024-12-26 16:00 UTC, pranjalg1331 commented
@mlodic, Please review.

2025-01-02 14:44 UTC, mlodic requested changes
please review the checklist, some important steps are missing

2025-01-02 14:44 UTC, mlodic commented on api_app/analyzers_manager/observable_analyzers/dns/dns_malicious_detectors/ultradns_malicious_detector.py
> +            raise AnalyzerRunException(f"An error occurred: {e}")
this is not needed cause the framework already manages it in this way (the upper class)

2025-01-02 14:44 UTC, mlodic commented on api_app/analyzers_manager/observable_analyzers/dns/dns_malicious_detectors/ultradns_malicious_detector.py
> +                    raise AnalyzerRunException("Connection to UltraDNS failed")
optimize this code cause redundant. I think that you could list both the nameservers together in the list

2025-01-02 14:44 UTC, mlodic commented on api_app/playbooks_manager/migrations/0057_add_ultradns_to_free_to_use.py
> +# This file is a part of IntelOwl https://github.com/intelowlproject/IntelOwl
please merge these 2 migrations in a single one

2025-01-02 14:44 UTC, mlodic commented on api_app/analyzers_manager/migrations/0143_analyzer_config_ultradns_malicious_detector.py
> +from django.db import migrations
merge these 2 migrations in a single one and adjust the migration numbers (pull from develop to get the most recent changes)

2025-01-03 04:32 UTC, pranjalg1331 commented on api_app/analyzers_manager/migrations/0143_analyzer_config_ultradns_malicious_detector.py
> +from django.db import migrations
@mlodic Should I merge them manually or there is an option to auto-generate migration for two analyzers in the same file?
Currently I was using this command `docker exec -ti intelowl_uwsgi python3 manage.py dumpplugin AnalyzerConfig <new_analyzer_name>`

2025-01-03 09:18 UTC, mlodic commented on api_app/analyzers_manager/migrations/0143_analyzer_config_ultradns_malicious_detector.py
> +from django.db import migrations
ok I don't want to overcomplicate things. I am more bothered about the 2 playbooks migrations. Try to merge them manually (it is easy), while leave these analyzers migrations separated for sake of simplicity

2025-01-04 08:11 UTC, pranjalg1331 commented on api_app/analyzers_manager/observable_analyzers/dns/dns_malicious_detectors/ultradns_malicious_detector.py
> +                    raise AnalyzerRunException("Connection to UltraDNS failed")
Updated

2025-01-07 09:55 UTC, mlodic commented
once the tests pass I'll merge this :)

2025-01-07 11:17 UTC, mlodic commented
please fix migration issues

2025-01-07 17:26 UTC, mlodic approved these changes

2025-01-07 17:26 UTC, merged