Added triage observable analyzer
intelowlproject/IntelOwl pull request #283
Opened 2020-12-08 20:38 UTC by m0mosenpai

# Description

Added triage analyzer for scanning observables - searching through existing reports via URL or Hash query; or submitting a sample for analysis via a URL. Also added documentation for both triage observable and file analyzers.

## Fixes
#142 

## Type of change
- [x] New feature (non-breaking change which adds functionality).

# Checklist

- [x] The pull request is for the branch develop
- [x] I changed the file [Usage](https://github.com/intelowlproject/IntelOwl/blob/master/docs/source/Usage.md) and [ReadMe](https://github.com/intelowlproject/IntelOwl/blob/master/README.md) if I added a new analyzer. 
- [x] I have added tests in the [Tests](https://github.com/intelowlproject/IntelOwl/blob/master/tests) folder. 
- [x] The tests gave 0 errors.
- [x] `Black` gave 0 errors.
- [x] `Flake` gave 0 errors.
- [ ] I squashed the commits into a single one.

# Real World Example
1. `submit` config paramenter - submitting file via url (similar report generated as triage file analyzer)
![image](https://user-images.githubusercontent.com/17424778/101536522-214b0200-39c0-11eb-9234-c1d75282777d.png)

2. `search` config parameter - searching for reports via hash.
![image](https://user-images.githubusercontent.com/17424778/101537670-e944be80-39c1-11eb-98f1-16b2a9f17e06.png)
50 results (default) (max 200) in same format as above followed by a `next` key. I haven't implemented pagination using `next` as of now. A bit confused on how to go about it since next contains a date-time stamp of sorts. 
![image](https://user-images.githubusercontent.com/17424778/101537783-142f1280-39c2-11eb-8686-d761e1f3517f.png)

3. `search` config parameter - searching for reports via URL.
I couldn't find a good example of this (a malicious url) but report should be similar to the hash case.

2020-12-09 10:13 UTC, Eshaan7 commented on api_app/script_analyzers/observable_analyzers/triage_search.py
> +            raise AnalyzerRunException(
should be [`AnalyzerConfigurationException`](https://github.com/intelowlproject/IntelOwl/blob/fa472db8c9b3d4c7ec5201ec552f6f928b076814/api_app/exceptions.py#L5)

2020-12-09 10:15 UTC, Eshaan7 commented on api_app/script_analyzers/observable_analyzers/triage_search.py
> +            raise AnalyzerRunException("unknown analysis type")
should be [`AnalyzerConfigurationException`](https://github.com/intelowlproject/IntelOwl/blob/fa472db8c9b3d4c7ec5201ec552f6f928b076814/api_app/exceptions.py#L5).

The error message should be something similar to [this](https://github.com/intelowlproject/IntelOwl/blob/1d1d61fd318c686776848d58733e6877d39b5ee1/api_app/script_analyzers/observable_analyzers/shodan.py#L32-L33).

2020-12-09 10:16 UTC, Eshaan7 commented on configuration/analyzer_config.json
> +      "soft_time_limit": 300
`soft_time_limit` should be outside of of `additional_config_param`

2020-12-09 10:20 UTC, Eshaan7 commented on tests/test_observables.py
> +    def test_triage_search(self, *args):
should duplicate this test for the case `test_triage_submit` passing `"{ analysis_type": "submit" }` as `additional_config_param`

2020-12-09 10:20 UTC, Eshaan7 commented on tests/test_observables.py
> +    def test_triage_search(self, *args):
should duplicate this test for the case `test_triage_submit` passing `"{ analysis_type": "submit" }`

2020-12-09 17:45 UTC, mlodic commented
Please `git rebase develop` to get recent changes on Continuous Integration management (Travis dropped support for OS projects so we had to move on). In this way, checks will trigger again with the new configuration. Thank you

2020-12-11 14:24 UTC, Eshaan7 requested changes

2020-12-12 11:29 UTC, Eshaan7 commented on configuration/analyzer_config.json
> +      "soft_time_limit": 300
please make same change on line number 985

2020-12-13 11:12 UTC, m0mosenpai commented
Please let me know if there's anything else to change else I'll squash the commits.

2020-12-14 13:32 UTC, Eshaan7 commented on configuration/analyzer_config.json
> +      "report_type": "overview"
should add `analysis_type: "submit"` parameter. Explicit is better than implicit.

2020-12-14 13:33 UTC, Eshaan7 commented on configuration/analyzer_config.json
>        "endpoint": "public",
should add `analysis_type: "search"` parameter. Explicit is better than implicit.

2020-12-14 13:38 UTC, Eshaan7 commented on configuration/analyzer_config.json
> +    "description": "analyze a url sample using triage sandbox environment",
add another key-value `"external_service": true,`

2020-12-14 13:39 UTC, Eshaan7 commented on configuration/analyzer_config.json
>      "type": "file",
add another key-value `"external_service": true,`

2020-12-14 19:17 UTC, merged