adding swagger documentation
intelowlproject/IntelOwl pull request #332
Opened 2021-01-27 18:38 UTC by spiderxm

Added Swagger and Redoc documentation for rest apis.

2021-01-28 08:20 UTC, mlodic requested changes
Thank you for your PR!

However it is really important that you read and follow the contributions guidelines.

Also please do not delete the PR template. You should compile it. Otherwise your contributions won't be considered. Everything you need to know is written there.

2021-01-28 19:04 UTC, Eshaan7 commented
We need to make this autogenerate for every commit with rest of the docs and host them publicly like: https://intelowl.readthedocs.io/api-docs. 

How can we achieve that?

2021-01-28 19:37 UTC, spiderxm commented
We can use the command
> python manage.py python manage.py generateschema 

This will generate open api definitions in yaml.
That can be used to make swagger documentation and serve them via different application.

2021-01-31 13:26 UTC, Eshaan7 commented
> This will generate open api definitions in yaml.
> That can be used to make swagger documentation and serve them via different application.

Okay so what we need to do is create a GH action (or readthedocs webhook) which builds the `.yml` schema and puts it into `/docs/source/` which then gets rendered using [`sphinx openapi extension`](https://github.com/sphinx-contrib/openapi) ? The catch here is that this action should take place before readthedocs build gets triggered for which you should find something in readthedocs documentation.

2021-01-31 13:27 UTC, Eshaan7 commented on api_app/urls.py
> +
please fix codefactor issue

2021-01-31 13:27 UTC, Eshaan7 commented on api_app/urls.py
> +schema_view = get_schema_view(
instead of adding this here, we should add a new file called `schemas.py` and add all this docs related code there.

2021-01-31 14:17 UTC, spiderxm commented
Will look into it

2021-02-12 11:27 UTC, Eshaan7 commented
https://github.com/sphinx-contrib/redoc/issues/15

2021-02-12 14:58 UTC, closed without merging