Fixes #613: New PR to Add Spyse analyzer for Spyse's API
intelowlproject/IntelOwl pull request #681
Opened 2021-09-01 19:12 UTC by Palash-Vishnani

This is the alternate updated PR of #667.

2021-09-02 06:47 UTC, Palash-Vishnani commented
@sp35 @eshaan7
Is there anything else that I need to do? Maybe the PR is ready now.

2021-09-02 08:20 UTC, sp35 approved these changes
LGTM, please show me a screenshot or json of results from this analyzer. Thank you.

2021-09-02 09:08 UTC, eshaan7 commented on api_app/analyzers_manager/observable_analyzers/spyse.py
> +            response = requests.get(self.base_url + uri, params=params)
I'd recommend again raising `AnalyzerRunException` in the `else` case. The thing is the code should _never_ reach this `else` clause in the first place but just so it does we can just raise the exception that `{self.observable_classification} not supported`.

2021-09-03 22:22 UTC, Palash-Vishnani commented
@sp35
Actually the thing is my docker isn't working from 2-3 days and I am trying to fix it's problem from soo long. And since my docker isn't running, IntelOwl is also facing problem in my PC. I really apologize for this, I'll try my best to solve the docker's issue, but till is there any other alternative way to test spyse analyzer.....?

2021-09-04 00:19 UTC, sp35 requested changes
Please do not ignore the PR instructions next time (re-added the checklist in description). You need to update docs for the new API Key.

2021-09-04 00:57 UTC, sp35 requested changes
@Palash-Vishnani I wanted to test out the changes on your behalf, but there is no free quota available. Maybe @eshaan7 can ask them to share one with you for testing out the integration. 

Till then, please do the changes requested, and let's keep the PR on hold. Thank you!

2021-09-04 00:57 UTC, sp35 commented on api_app/analyzers_manager/observable_analyzers/spyse.py
> +        params = {"key": self.__api_key}
This is incorrect. The [docs](https://spyse.com/api) say it requires an header instead.

`Authorization: Bearer 776b9620-e645-4f80-81e0-e45eebdade06`

2021-09-04 13:17 UTC, Palash-Vishnani commented
Bravvoooo!!! I am up and running. I'll soon send a commit after updating env_file_app_template, env_file_app_ci and Installation.md docs.
![spyse](https://user-images.githubusercontent.com/81798761/132095723-76a3c1c9-03f3-4fc1-88bc-a3f839cfacd4.JPG)

2021-09-05 05:58 UTC, Palash-Vishnani commented
@eshaan7 @sp35 @m0mosenpai 
Guys my docker is working fine. Also my analysis are running but not getting completed, and the output is something like this:

![analysis](https://user-images.githubusercontent.com/81798761/132117022-d5f5c595-093b-4447-8aa7-9ce78615f3b6.JPG)

I am getting this output for every kinds off analysis. Can any of you please suggest me the solution for this and why is this happening??

2021-09-05 06:05 UTC, Palash-Vishnani commented
@eshaan7 @sp35 @m0mosenpai 
Guys my docker is working fine. Also my analysis are running but not getting completed, and the output is something like this:

![analysis2](https://user-images.githubusercontent.com/81798761/132117247-62e9821e-ecd2-4384-9815-f7033c629103.JPG)


I am getting this output for every kinds off analysis though I have the API keys. Can any of you please suggest me the solution for this and why is this happening??

2021-09-06 07:28 UTC, eshaan7 commented
> @Palash-Vishnani I wanted to test out the changes on your behalf, but there is no free quota available. Maybe @eshaan7 can ask them to share one with you for testing out the integration.
> 
> Till then, please do the changes requested, and let's keep the PR on hold. Thank you!

I have asked them. Let's see what they say.

2021-09-08 11:43 UTC, eshaan7 commented on api_app/analyzers_manager/observable_analyzers/spyse.py
> +            else:
under the `generic`, we can also add support for the CVE endpoint. https://spyse-dev.readme.io/reference/cves

2021-09-08 15:21 UTC, eshaan7 commented
Hey, @Palash-Vishnani. I have just pushed fixes to this PR completing the changes.

2021-09-08 15:31 UTC, Palash-Vishnani commented
@eshaan7 
Ohh Ok thanks soo..do I have to do anything else? Modifications or anything?

2021-09-08 16:07 UTC, eshaan7 commented
> @eshaan7
> Ohh Ok thanks soo..do I have to do anything else? Modifications or anything?

Nope. But feel free to pick up any other issue if you wish to.

2021-09-08 16:24 UTC, merged

2021-09-08 17:19 UTC, Palash-Vishnani commented
Hey @eshaan7 the thing is, I thought that my name will get displayed in the contributors list, as my pull request and our commit got merged in this repository by you. But I can't see my name in there, why so?? And sorry to disturb you for this little thing.😅

2021-09-08 18:42 UTC, eshaan7 commented
> But I can't see my name in there, why so??

The contributors list is picked up from the `master` branch. The latest changes are not in `master` branch yet only `develop`. That's why.